// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegionsService.proto

package com.example.grpc;

public final class RegionsServiceOuterClass {
  private RegionsServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AreaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.grpc.Area)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string x = 1;</code>
     */
    java.lang.String getX();
    /**
     * <code>string x = 1;</code>
     */
    com.google.protobuf.ByteString
        getXBytes();

    /**
     * <code>string y = 2;</code>
     */
    java.lang.String getY();
    /**
     * <code>string y = 2;</code>
     */
    com.google.protobuf.ByteString
        getYBytes();
  }
  /**
   * Protobuf type {@code com.example.grpc.Area}
   */
  public  static final class Area extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.grpc.Area)
      AreaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Area.newBuilder() to construct.
    private Area(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Area() {
      x_ = "";
      y_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Area();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Area(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              x_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              y_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.RegionsServiceOuterClass.internal_static_com_example_grpc_Area_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.RegionsServiceOuterClass.internal_static_com_example_grpc_Area_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.RegionsServiceOuterClass.Area.class, com.example.grpc.RegionsServiceOuterClass.Area.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private volatile java.lang.Object x_;
    /**
     * <code>string x = 1;</code>
     */
    public java.lang.String getX() {
      java.lang.Object ref = x_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        x_ = s;
        return s;
      }
    }
    /**
     * <code>string x = 1;</code>
     */
    public com.google.protobuf.ByteString
        getXBytes() {
      java.lang.Object ref = x_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        x_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int Y_FIELD_NUMBER = 2;
    private volatile java.lang.Object y_;
    /**
     * <code>string y = 2;</code>
     */
    public java.lang.String getY() {
      java.lang.Object ref = y_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        y_ = s;
        return s;
      }
    }
    /**
     * <code>string y = 2;</code>
     */
    public com.google.protobuf.ByteString
        getYBytes() {
      java.lang.Object ref = y_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        y_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getXBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, x_);
      }
      if (!getYBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, y_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getXBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, x_);
      }
      if (!getYBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, y_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.grpc.RegionsServiceOuterClass.Area)) {
        return super.equals(obj);
      }
      com.example.grpc.RegionsServiceOuterClass.Area other = (com.example.grpc.RegionsServiceOuterClass.Area) obj;

      if (!getX()
          .equals(other.getX())) return false;
      if (!getY()
          .equals(other.getY())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX().hashCode();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.grpc.RegionsServiceOuterClass.Area parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.RegionsServiceOuterClass.Area parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.RegionsServiceOuterClass.Area parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.RegionsServiceOuterClass.Area parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.RegionsServiceOuterClass.Area parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.RegionsServiceOuterClass.Area parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.RegionsServiceOuterClass.Area parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.RegionsServiceOuterClass.Area parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.RegionsServiceOuterClass.Area parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.grpc.RegionsServiceOuterClass.Area parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.RegionsServiceOuterClass.Area parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.RegionsServiceOuterClass.Area parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.grpc.RegionsServiceOuterClass.Area prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.grpc.Area}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.grpc.Area)
        com.example.grpc.RegionsServiceOuterClass.AreaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.grpc.RegionsServiceOuterClass.internal_static_com_example_grpc_Area_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.grpc.RegionsServiceOuterClass.internal_static_com_example_grpc_Area_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.grpc.RegionsServiceOuterClass.Area.class, com.example.grpc.RegionsServiceOuterClass.Area.Builder.class);
      }

      // Construct using com.example.grpc.RegionsServiceOuterClass.Area.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = "";

        y_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.grpc.RegionsServiceOuterClass.internal_static_com_example_grpc_Area_descriptor;
      }

      @java.lang.Override
      public com.example.grpc.RegionsServiceOuterClass.Area getDefaultInstanceForType() {
        return com.example.grpc.RegionsServiceOuterClass.Area.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.grpc.RegionsServiceOuterClass.Area build() {
        com.example.grpc.RegionsServiceOuterClass.Area result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.grpc.RegionsServiceOuterClass.Area buildPartial() {
        com.example.grpc.RegionsServiceOuterClass.Area result = new com.example.grpc.RegionsServiceOuterClass.Area(this);
        result.x_ = x_;
        result.y_ = y_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.grpc.RegionsServiceOuterClass.Area) {
          return mergeFrom((com.example.grpc.RegionsServiceOuterClass.Area)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.grpc.RegionsServiceOuterClass.Area other) {
        if (other == com.example.grpc.RegionsServiceOuterClass.Area.getDefaultInstance()) return this;
        if (!other.getX().isEmpty()) {
          x_ = other.x_;
          onChanged();
        }
        if (!other.getY().isEmpty()) {
          y_ = other.y_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.grpc.RegionsServiceOuterClass.Area parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.grpc.RegionsServiceOuterClass.Area) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object x_ = "";
      /**
       * <code>string x = 1;</code>
       */
      public java.lang.String getX() {
        java.lang.Object ref = x_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          x_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string x = 1;</code>
       */
      public com.google.protobuf.ByteString
          getXBytes() {
        java.lang.Object ref = x_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          x_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string x = 1;</code>
       */
      public Builder setX(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = getDefaultInstance().getX();
        onChanged();
        return this;
      }
      /**
       * <code>string x = 1;</code>
       */
      public Builder setXBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        x_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object y_ = "";
      /**
       * <code>string y = 2;</code>
       */
      public java.lang.String getY() {
        java.lang.Object ref = y_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          y_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string y = 2;</code>
       */
      public com.google.protobuf.ByteString
          getYBytes() {
        java.lang.Object ref = y_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          y_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string y = 2;</code>
       */
      public Builder setY(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = getDefaultInstance().getY();
        onChanged();
        return this;
      }
      /**
       * <code>string y = 2;</code>
       */
      public Builder setYBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        y_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.grpc.Area)
    }

    // @@protoc_insertion_point(class_scope:com.example.grpc.Area)
    private static final com.example.grpc.RegionsServiceOuterClass.Area DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.grpc.RegionsServiceOuterClass.Area();
    }

    public static com.example.grpc.RegionsServiceOuterClass.Area getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Area>
        PARSER = new com.google.protobuf.AbstractParser<Area>() {
      @java.lang.Override
      public Area parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Area(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Area> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Area> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.grpc.RegionsServiceOuterClass.Area getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SaveRegionsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.grpc.SaveRegionsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.com.example.grpc.Area area = 2;</code>
     */
    boolean hasArea();
    /**
     * <code>.com.example.grpc.Area area = 2;</code>
     */
    com.example.grpc.RegionsServiceOuterClass.Area getArea();
    /**
     * <code>.com.example.grpc.Area area = 2;</code>
     */
    com.example.grpc.RegionsServiceOuterClass.AreaOrBuilder getAreaOrBuilder();
  }
  /**
   * Protobuf type {@code com.example.grpc.SaveRegionsRequest}
   */
  public  static final class SaveRegionsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.grpc.SaveRegionsRequest)
      SaveRegionsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SaveRegionsRequest.newBuilder() to construct.
    private SaveRegionsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SaveRegionsRequest() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SaveRegionsRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SaveRegionsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              com.example.grpc.RegionsServiceOuterClass.Area.Builder subBuilder = null;
              if (area_ != null) {
                subBuilder = area_.toBuilder();
              }
              area_ = input.readMessage(com.example.grpc.RegionsServiceOuterClass.Area.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(area_);
                area_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.RegionsServiceOuterClass.internal_static_com_example_grpc_SaveRegionsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.RegionsServiceOuterClass.internal_static_com_example_grpc_SaveRegionsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest.class, com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AREA_FIELD_NUMBER = 2;
    private com.example.grpc.RegionsServiceOuterClass.Area area_;
    /**
     * <code>.com.example.grpc.Area area = 2;</code>
     */
    public boolean hasArea() {
      return area_ != null;
    }
    /**
     * <code>.com.example.grpc.Area area = 2;</code>
     */
    public com.example.grpc.RegionsServiceOuterClass.Area getArea() {
      return area_ == null ? com.example.grpc.RegionsServiceOuterClass.Area.getDefaultInstance() : area_;
    }
    /**
     * <code>.com.example.grpc.Area area = 2;</code>
     */
    public com.example.grpc.RegionsServiceOuterClass.AreaOrBuilder getAreaOrBuilder() {
      return getArea();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (area_ != null) {
        output.writeMessage(2, getArea());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (area_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getArea());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest)) {
        return super.equals(obj);
      }
      com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest other = (com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (hasArea() != other.hasArea()) return false;
      if (hasArea()) {
        if (!getArea()
            .equals(other.getArea())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasArea()) {
        hash = (37 * hash) + AREA_FIELD_NUMBER;
        hash = (53 * hash) + getArea().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.grpc.SaveRegionsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.grpc.SaveRegionsRequest)
        com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.grpc.RegionsServiceOuterClass.internal_static_com_example_grpc_SaveRegionsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.grpc.RegionsServiceOuterClass.internal_static_com_example_grpc_SaveRegionsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest.class, com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest.Builder.class);
      }

      // Construct using com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        if (areaBuilder_ == null) {
          area_ = null;
        } else {
          area_ = null;
          areaBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.grpc.RegionsServiceOuterClass.internal_static_com_example_grpc_SaveRegionsRequest_descriptor;
      }

      @java.lang.Override
      public com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest getDefaultInstanceForType() {
        return com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest build() {
        com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest buildPartial() {
        com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest result = new com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest(this);
        result.name_ = name_;
        if (areaBuilder_ == null) {
          result.area_ = area_;
        } else {
          result.area_ = areaBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest) {
          return mergeFrom((com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest other) {
        if (other == com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasArea()) {
          mergeArea(other.getArea());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.example.grpc.RegionsServiceOuterClass.Area area_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.grpc.RegionsServiceOuterClass.Area, com.example.grpc.RegionsServiceOuterClass.Area.Builder, com.example.grpc.RegionsServiceOuterClass.AreaOrBuilder> areaBuilder_;
      /**
       * <code>.com.example.grpc.Area area = 2;</code>
       */
      public boolean hasArea() {
        return areaBuilder_ != null || area_ != null;
      }
      /**
       * <code>.com.example.grpc.Area area = 2;</code>
       */
      public com.example.grpc.RegionsServiceOuterClass.Area getArea() {
        if (areaBuilder_ == null) {
          return area_ == null ? com.example.grpc.RegionsServiceOuterClass.Area.getDefaultInstance() : area_;
        } else {
          return areaBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.example.grpc.Area area = 2;</code>
       */
      public Builder setArea(com.example.grpc.RegionsServiceOuterClass.Area value) {
        if (areaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          area_ = value;
          onChanged();
        } else {
          areaBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.example.grpc.Area area = 2;</code>
       */
      public Builder setArea(
          com.example.grpc.RegionsServiceOuterClass.Area.Builder builderForValue) {
        if (areaBuilder_ == null) {
          area_ = builderForValue.build();
          onChanged();
        } else {
          areaBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.example.grpc.Area area = 2;</code>
       */
      public Builder mergeArea(com.example.grpc.RegionsServiceOuterClass.Area value) {
        if (areaBuilder_ == null) {
          if (area_ != null) {
            area_ =
              com.example.grpc.RegionsServiceOuterClass.Area.newBuilder(area_).mergeFrom(value).buildPartial();
          } else {
            area_ = value;
          }
          onChanged();
        } else {
          areaBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.example.grpc.Area area = 2;</code>
       */
      public Builder clearArea() {
        if (areaBuilder_ == null) {
          area_ = null;
          onChanged();
        } else {
          area_ = null;
          areaBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.example.grpc.Area area = 2;</code>
       */
      public com.example.grpc.RegionsServiceOuterClass.Area.Builder getAreaBuilder() {
        
        onChanged();
        return getAreaFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.example.grpc.Area area = 2;</code>
       */
      public com.example.grpc.RegionsServiceOuterClass.AreaOrBuilder getAreaOrBuilder() {
        if (areaBuilder_ != null) {
          return areaBuilder_.getMessageOrBuilder();
        } else {
          return area_ == null ?
              com.example.grpc.RegionsServiceOuterClass.Area.getDefaultInstance() : area_;
        }
      }
      /**
       * <code>.com.example.grpc.Area area = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.grpc.RegionsServiceOuterClass.Area, com.example.grpc.RegionsServiceOuterClass.Area.Builder, com.example.grpc.RegionsServiceOuterClass.AreaOrBuilder> 
          getAreaFieldBuilder() {
        if (areaBuilder_ == null) {
          areaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.example.grpc.RegionsServiceOuterClass.Area, com.example.grpc.RegionsServiceOuterClass.Area.Builder, com.example.grpc.RegionsServiceOuterClass.AreaOrBuilder>(
                  getArea(),
                  getParentForChildren(),
                  isClean());
          area_ = null;
        }
        return areaBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.grpc.SaveRegionsRequest)
    }

    // @@protoc_insertion_point(class_scope:com.example.grpc.SaveRegionsRequest)
    private static final com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest();
    }

    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SaveRegionsRequest>
        PARSER = new com.google.protobuf.AbstractParser<SaveRegionsRequest>() {
      @java.lang.Override
      public SaveRegionsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SaveRegionsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SaveRegionsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SaveRegionsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.grpc.RegionsServiceOuterClass.SaveRegionsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SaveRegionsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.grpc.SaveRegionsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string stringId = 1;</code>
     */
    java.lang.String getStringId();
    /**
     * <code>string stringId = 1;</code>
     */
    com.google.protobuf.ByteString
        getStringIdBytes();
  }
  /**
   * Protobuf type {@code com.example.grpc.SaveRegionsResponse}
   */
  public  static final class SaveRegionsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.grpc.SaveRegionsResponse)
      SaveRegionsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SaveRegionsResponse.newBuilder() to construct.
    private SaveRegionsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SaveRegionsResponse() {
      stringId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SaveRegionsResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SaveRegionsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              stringId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.RegionsServiceOuterClass.internal_static_com_example_grpc_SaveRegionsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.RegionsServiceOuterClass.internal_static_com_example_grpc_SaveRegionsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse.class, com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse.Builder.class);
    }

    public static final int STRINGID_FIELD_NUMBER = 1;
    private volatile java.lang.Object stringId_;
    /**
     * <code>string stringId = 1;</code>
     */
    public java.lang.String getStringId() {
      java.lang.Object ref = stringId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringId_ = s;
        return s;
      }
    }
    /**
     * <code>string stringId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStringIdBytes() {
      java.lang.Object ref = stringId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStringIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stringId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStringIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stringId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse)) {
        return super.equals(obj);
      }
      com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse other = (com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse) obj;

      if (!getStringId()
          .equals(other.getStringId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STRINGID_FIELD_NUMBER;
      hash = (53 * hash) + getStringId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.grpc.SaveRegionsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.grpc.SaveRegionsResponse)
        com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.grpc.RegionsServiceOuterClass.internal_static_com_example_grpc_SaveRegionsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.grpc.RegionsServiceOuterClass.internal_static_com_example_grpc_SaveRegionsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse.class, com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse.Builder.class);
      }

      // Construct using com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        stringId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.grpc.RegionsServiceOuterClass.internal_static_com_example_grpc_SaveRegionsResponse_descriptor;
      }

      @java.lang.Override
      public com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse getDefaultInstanceForType() {
        return com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse build() {
        com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse buildPartial() {
        com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse result = new com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse(this);
        result.stringId_ = stringId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse) {
          return mergeFrom((com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse other) {
        if (other == com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse.getDefaultInstance()) return this;
        if (!other.getStringId().isEmpty()) {
          stringId_ = other.stringId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object stringId_ = "";
      /**
       * <code>string stringId = 1;</code>
       */
      public java.lang.String getStringId() {
        java.lang.Object ref = stringId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stringId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stringId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStringIdBytes() {
        java.lang.Object ref = stringId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stringId = 1;</code>
       */
      public Builder setStringId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stringId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stringId = 1;</code>
       */
      public Builder clearStringId() {
        
        stringId_ = getDefaultInstance().getStringId();
        onChanged();
        return this;
      }
      /**
       * <code>string stringId = 1;</code>
       */
      public Builder setStringIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stringId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.grpc.SaveRegionsResponse)
    }

    // @@protoc_insertion_point(class_scope:com.example.grpc.SaveRegionsResponse)
    private static final com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse();
    }

    public static com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SaveRegionsResponse>
        PARSER = new com.google.protobuf.AbstractParser<SaveRegionsResponse>() {
      @java.lang.Override
      public SaveRegionsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SaveRegionsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SaveRegionsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SaveRegionsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.grpc.RegionsServiceOuterClass.SaveRegionsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_Area_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_Area_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_SaveRegionsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_SaveRegionsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_SaveRegionsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_SaveRegionsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024RegionsService.proto\022\020com.example.grpc" +
      "\"\034\n\004Area\022\t\n\001x\030\001 \001(\t\022\t\n\001y\030\002 \001(\t\"H\n\022SaveRe" +
      "gionsRequest\022\014\n\004name\030\001 \001(\t\022$\n\004area\030\002 \001(\013" +
      "2\026.com.example.grpc.Area\"\'\n\023SaveRegionsR" +
      "esponse\022\020\n\010stringId\030\001 \001(\t2l\n\016RegionsServ" +
      "ice\022Z\n\013saveRegions\022$.com.example.grpc.Sa" +
      "veRegionsRequest\032%.com.example.grpc.Save" +
      "RegionsResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_grpc_Area_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_Area_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_Area_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_com_example_grpc_SaveRegionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpc_SaveRegionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_SaveRegionsRequest_descriptor,
        new java.lang.String[] { "Name", "Area", });
    internal_static_com_example_grpc_SaveRegionsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_grpc_SaveRegionsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_SaveRegionsResponse_descriptor,
        new java.lang.String[] { "StringId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
